# NB: any sampler without a revcomp_samplesheet_i5_index key will not be
# available to users when making sample sheets, because we don't know what that
# value should be, and it's better to error than to silently do the wrong thing
HiSeq1500:
    model_name: 'Illumina HiSeq 1500'
    revcomp_samplesheet_i5_index: false
HiSeq2500:
    model_name: 'Illumina HiSeq 2500'
    revcomp_samplesheet_i5_index: false
    machine_prefix: 'D'
    profile_name: 'HiSeq 2500'
HiSeq3000:
    model_name: 'Illumina HiSeq 3000'
    revcomp_samplesheet_i5_index: true
HiSeq4000:
    model_name: 'Illumina HiSeq 4000'
    revcomp_samplesheet_i5_index: true
    machine_prefix: 'K'
    profile_name: 'HiSeq 4000'
iSeq:
    model_name: 'Illumina iSeq'
    revcomp_samplesheet_i5_index: true
    machine_prefix: 'FS'
    delete_settings:
        - "MaskShortReads"
        - "OverrideCycles"
    profile_name: 'iSeq'
MiniSeq:
    model_name: 'Illumina MiniSeq'
    # Per the Illumina Knowledge Base's “Guidelines for reverse complementing
    # i5 sequences for demultiplexing”,
    # https://knowledge.illumina.com/software/general/software-general-reference_material-list/000001800
    # MiniSeq Rapid Kit always use forward orientation, so if we were to use
    # those, we would need to modify this value.
    revcomp_samplesheet_i5_index: true
    machine_prefix: 'MN'
    profile_name: 'MiniSeq'
MiSeq:
    model_name: 'Illumina MiSeq'
    revcomp_samplesheet_i5_index: false
    machine_prefix: 'M'
    profile_name: 'MiSeq'
MiSeqi100:
    model_name: 'Illumina MiSeq i100'
    machine_prefix: 'SH'
    # Per the Illumina Knowledge Base's “Guidelines for reverse complementing
    # i5 sequences for demultiplexing”,
    # https://knowledge.illumina.com/software/general/software-general-reference_material-list/000001800
    # no revcomping of i5 index sequences is required for MiSeq i100 *IF* we
    # are using standalone BCL convert.  If we ever change how we are doing
    # FASTQ generation, we may need to change this.
    profile_name: 'MiSeq i100'
NextSeq:
    model_name: 'Illumina NextSeq 500/550'
    revcomp_samplesheet_i5_index: true
NovaSeq6000:
    model_name: 'Illumina NovaSeq 6000'
    revcomp_samplesheet_i5_index: true
    machine_prefix: 'A'
    profile_name: 'NovaSeq 6000'
NovaSeqX:
    model_name: 'Illumina NovaSeq X'
    # Per the Illumina Knowledge Base's “Guidelines for reverse complementing
    # i5 sequences for demultiplexing",
    # https://knowledge.illumina.com/software/general/software-general-reference_material-list/000001800
    # NovaSeqX/XPlus do not require reverse complementing of i5 index sequences
    # *for standalone BCL convert*.  They *do* require it for standalone
    # bcl2fastq or BSSH FASTQ generation, so if we ever change how we are doing
    # FASTQ generation, we may need to change this.
    revcomp_samplesheet_i5_index: false
    machine_prefix: 'LH'
    profile_name: 'NovaSeq X'
NovaSeqXPlus:
    model_name: 'Illumina NovaSeq X Plus'
    # See above comment for NovaSeqX re: revcomp_samplesheet_i5_index
    revcomp_samplesheet_i5_index: false
# NB: InstrumentUtils class in qp-klp used to define
# an 'SN': 'RapidRun' machine prefix, but as of 20250703,
# we don't seem to have any data with that prefix.  The
# qp-klp comments say RapidRun was HiSeq 2500 (?) which is
# confusing, so not adding it here until/unless we need it.
